import Foundation

// Global localization extension that respects the app's language setting
extension String {
    var localized: String {
        let language = LanguageManager.shared.currentLanguage
        print("🌐 Localizing '\(self)' for language: \(language.rawValue)")
        
        // Check Korean first
        if language == .korean {
            if let translation = koreanStrings[self] {
                print("✅ Found Korean: '\(translation)'")
                return translation
            }
            print("❌ No Korean translation for '\(self)'")
        }
        
        // Check English
        if let translation = englishStrings[self] {
            print("✅ Found English: '\(translation)'")
            return translation
        }
        
        print("⚠️ Returning key itself: '\(self)'")
        return self
    }
}

// English translations
private let englishStrings: [String: String] = [
    "Settings": "Settings",
    "Profile": "Profile",
    "Heading": "Heading",
    "Subheading": "Subheading",
    "Sub-subheading": "Sub-subheading",
    "Body": "Body",
    "Make public": "Make public",
    "Writing Archive": "Writing Archive",
    "Today's Keyword": "Today's Keyword",
    "Start Writing": "Start Writing",
    "Edit Profile": "Edit Profile",
    "Account": "Account",
    "Links": "Links",
    "Done": "Done",
    "Cancel": "Cancel",
    "Save": "Save",
    "Delete": "Delete",
    "Edit": "Edit",
    "Close": "Close",
    "Back": "Back",
    "Drafts": "Drafts",
    "Next": "Next",
    "Continue": "Continue",
    "Loading": "Loading...",
    "Error": "Error",
    "Success": "Success",
    "OK": "OK",
    "Yes": "Yes",
    "No": "No",
    "Feed": "Feed",
    "Write": "Write",
    "Sign In": "Sign In",
    "Sign Up": "Sign Up",
    "Sign Out": "Sign Out",
    "Email": "Email",
    "Password": "Password",
    "Create Account": "Create Account",
    "Day Streak": "Day Streak",
    "Words Written": "Words Written",
    "Published": "Published",
    "words": "words",
    "Title (optional)": "Title (optional)",
    "Save Draft": "Save Draft",
    "Publish": "Publish",
    "Following": "Following",
    "Discover": "Discover",
    "Recent": "Recent",
    "Trending": "Trending",
    "My Essays": "My Essays",
    "Comments": "Comments",
    "Add a comment...": "Add a comment...",
    "Post": "Post",
    "Likes": "Likes",
    "Like": "Like",
    "Unlike": "Unlike",
    "Your Essays": "Your Essays",
    "See All": "See All",
    "Essays": "Essays",
    "Followers": "Followers",
    "Anonymous": "Anonymous",
    "Untitled": "Untitled",
    "Writer": "Writer",
    "Filter": "Filter",
    "Prompt": "Prompt",
    "Display Name": "Display Name",
    "Bio": "Bio",
    "Username": "Username",
    "Save Changes": "Save Changes",
    "All Essays": "All Essays",
    "No essays yet": "No essays yet",
    "Start writing to see your essays here": "Start writing to see your essays here",
    "Essay": "Essay",
    "No essays on this day": "No essays on this day",
    "Write now": "Write now",
    "Appearance": "Appearance",
    "Font": "Font",
    "Font Size": "Font Size",
    "Preview": "Preview",
    "Language": "Language",
    "About": "About",
    "Version": "Version",
    "Fonts": "Fonts",
    "Choose Font": "Choose Font",
    "Select Language": "Select Language",
    "Choose your preferred language": "Choose your preferred language",
    "You can change this later in settings": "You can change this later in settings",
    "Notifications": "Notifications",
    "Daily Reminder": "Daily Reminder",
    "On": "On",
    "Off": "Off",
    "Backup & Export": "Backup & Export",
    "Backup to iCloud": "Backup to iCloud",
    "Export Essays": "Export Essays",
    "Delete Account": "Delete Account",
    "Instagram": "Instagram",
    "Threads": "Threads",
    "Twitter/X": "Twitter/X",
    "Blog URL": "Blog URL",
    "Brunch URL": "Brunch URL",
    "Title": "Title",
    "Content": "Content",
    "Last 30 Days": "Last 30 Days",
    "Written": "Written",
    "Missed": "Missed",
    "Writing Analytics": "Writing Analytics",
    "Total Words": "Total Words",
    "Essays Written": "Essays Written",
    "Avg Words/Essay": "Avg Words/Essay",
    "Writing Activity": "Writing Activity",
    "Weekly Pattern": "Weekly Pattern",
    "Best Writing Day": "Best Writing Day",
    "You write most on": "You write most on",
    "Time Range": "Time Range",
    "Week": "Week",
    "Month": "Month",
    "Year": "Year",
    "All Time": "All Time",
    "Challenges": "Challenges",
    "Completed": "Completed",
    "Start your first challenge!": "Start your first challenge!",
    "Amazing! You've completed all challenges!": "Amazing! You've completed all challenges!",
    "more to go!": "more to go!",
    "Done!": "Done!",
    "Challenge Complete!": "Challenge Complete!",
    "Awesome!": "Awesome!",
    "First Steps": "First Steps",
    "Write your first essay": "Write your first essay",
    "On a Roll": "On a Roll",
    "Write for 3 days in a row": "Write for 3 days in a row",
    "Week Warrior": "Week Warrior",
    "Write for 7 days in a row": "Write for 7 days in a row",
    "Month Master": "Month Master",
    "Write for 30 days in a row": "Write for 30 days in a row",
    "Word Builder": "Word Builder",
    "Write 1,000 words total": "Write 1,000 words total",
    "Word Smith": "Word Smith",
    "Write 10,000 words total": "Write 10,000 words total",
    "Word Master": "Word Master",
    "Write 50,000 words total": "Write 50,000 words total",
    "Prolific Writer": "Prolific Writer",
    "Write 10 essays": "Write 10 essays",
    "Essay Machine": "Essay Machine",
    "Write 50 essays": "Write 50 essays",
    "Going Public": "Going Public",
    "Publish your first public essay": "Publish your first public essay",
    "Community Contributor": "Community Contributor",
    "Publish 10 public essays": "Publish 10 public essays",
    "Early Bird": "Early Bird",
    "Write before 9 AM": "Write before 9 AM",
    "Night Owl": "Night Owl",
    "Write after 10 PM": "Write after 10 PM",
    "Friends": "Friends",
    "My Friends": "My Friends",
    "Friend Requests": "Friend Requests",
    "Add Friend": "Add Friend",
    "Send Friend Request": "Send Friend Request",
    "Request Sent": "Request Sent",
    "Already Friends": "Already Friends",
    "Enter username": "Enter username",
    "Search Result": "Search Result",
    "Search": "Search",
    "wants to be friends": "wants to be friends",
    "No Friends Yet": "No Friends Yet",
    "Add friends to share your essays privately": "Add friends to share your essays privately",
    "Share Essay": "Share Essay",
    "Select Friends": "Select Friends",
    "Shared!": "Shared!",
    "Successfully shared with %d friends!": "Successfully shared with %d friends!",
    "No keyword": "No keyword",
    "No friends yet. Add friends to share your writing!": "No friends yet. Add friends to share your writing!",
    "User not found": "User not found",
    "%d friends": "%d friends",
    "Who can see this?": "Who can see this?",
    "Visibility": "Visibility",
    "Ready to Publish?": "Ready to Publish?",
    "Select Visibility": "Select Visibility",
    "Publish Essay": "Publish Essay",
    "Save as Draft": "Save as Draft",
    "Edit Draft": "Edit Draft",
    "Edit Essay": "Edit Essay",
    "Your essay will be published as %@": "Your essay will be published as %@",
    "Create Book": "Create Book",
    "Select Essays": "Select Essays",
    "PDF": "PDF",
    "EPUB": "EPUB",
    "Book Title": "Book Title",
    "Author Name": "Author Name",
    "Book Cover": "Book Cover",
    "Include Table of Contents": "Include Table of Contents",
    "Include Dates": "Include Dates",
    "Export as": "Export as",
    "Generating...": "Generating...",
    "Book Created!": "Book Created!",
    "Your book has been saved to Files": "Your book has been saved to Files",
    "Open in Files": "Open in Files",
    "Share Book": "Share Book",
    "%d essays selected": "%d essays selected",
    "Select at least one essay": "Select at least one essay",
    "Table of Contents": "Table of Contents",
    "Essay %d": "Essay %d"
]

// Korean translations
private let koreanStrings: [String: String] = [
    "Settings": "설정",
    "Profile": "프로필",
    "Heading": "제목",
    "Subheading": "머리말",
    "Sub-subheading": "부머리말",
    "Body": "본문",
    "Make public": "공개하기",
    "Writing Archive": "글 보관함",
    "Today's Keyword": "오늘의 키워드",
    "Start Writing": "글쓰기 시작",
    "Edit Profile": "프로필 편집",
    "Account": "계정",
    "Links": "링크",
    "Done": "완료",
    "Cancel": "취소",
    "Save": "저장",
    "Delete": "삭제",
    "Edit": "편집",
    "Close": "닫기",
    "Back": "뒤로",
    "Drafts": "임시저장",
    "Next": "다음",
    "Continue": "계속하기",
    "Loading": "로딩 중...",
    "Error": "오류",
    "Success": "성공",
    "OK": "확인",
    "Yes": "예",
    "No": "아니오",
    "Feed": "피드",
    "Write": "쓰기",
    "Sign In": "로그인",
    "Sign Up": "회원가입",
    "Sign Out": "로그아웃",
    "Email": "이메일",
    "Password": "비밀번호",
    "Create Account": "계정 만들기",
    "Day Streak": "연속 일수",
    "Words Written": "작성한 단어",
    "Published": "게시한 글",
    "words": "자",
    "Title (optional)": "제목 (선택사항)",
    "Save Draft": "임시 저장",
    "Publish": "게시하기",
    "Following": "팔로잉",
    "Discover": "탐색",
    "Recent": "최신",
    "Trending": "인기",
    "My Essays": "내 글",
    "Comments": "댓글",
    "Add a comment...": "댓글을 입력하세요...",
    "Post": "게시",
    "Likes": "좋아요",
    "Like": "좋아요",
    "Unlike": "좋아요 취소",
    "Your Essays": "내 글",
    "See All": "전체보기",
    "Essays": "글",
    "Followers": "팔로워",
    "Anonymous": "익명",
    "Untitled": "제목 없음",
    "Writer": "작가",
    "Filter": "필터",
    "Prompt": "주제",
    "Display Name": "표시 이름",
    "Bio": "소개",
    "Username": "사용자명",
    "Save Changes": "변경사항 저장",
    "All Essays": "전체 글",
    "No essays yet": "아직 작성한 글이 없습니다",
    "Start writing to see your essays here": "글을 작성하면 여기에 표시됩니다",
    "Essay": "글",
    "No essays on this day": "이 날 작성한 글이 없습니다",
    "Write now": "지금 쓰기",
    "Appearance": "외형",
    "Font": "글꼴",
    "Font Size": "글꼴 크기",
    "Preview": "미리보기",
    "Language": "언어",
    "About": "정보",
    "Version": "버전",
    "Fonts": "글꼴",
    "Choose Font": "글꼴 선택",
    "Select Language": "언어 선택",
    "Choose your preferred language": "원하는 언어를 선택하세요",
    "You can change this later in settings": "설정에서 나중에 변경할 수 있습니다",
    "Notifications": "알림",
    "Daily Reminder": "일일 알림",
    "On": "켜짐",
    "Off": "꺼짐",
    "Backup & Export": "백업 및 내보내기",
    "Backup to iCloud": "iCloud에 백업",
    "Export Essays": "글 내보내기",
    "Delete Account": "회원탈퇴",
    "Instagram": "인스타그램",
    "Threads": "스레즈",
    "Twitter/X": "트위터/X",
    "Blog URL": "블로그 URL",
    "Brunch URL": "브런치 URL",
    "Title": "제목",
    "Content": "내용",
    "Last 30 Days": "최근 30일",
    "Written": "작성함",
    "Missed": "놓침",
    "Writing Analytics": "글쓰기 분석",
    "Total Words": "총 단어",
    "Essays Written": "작성한 글",
    "Avg Words/Essay": "평균 단어/글",
    "Writing Activity": "글쓰기 활동",
    "Weekly Pattern": "주간 패턴",
    "Best Writing Day": "최고의 글쓰기 요일",
    "You write most on": "당신은",
    "Time Range": "기간",
    "Week": "주",
    "Month": "월",
    "Year": "년",
    "All Time": "전체",
    "Challenges": "도전",
    "Completed": "완료",
    "Start your first challenge!": "첫 번째 도전을 시작하세요!",
    "Amazing! You've completed all challenges!": "대단해요! 모든 도전을 완료했습니다!",
    "more to go!": "개 남았습니다!",
    "Done!": "완료!",
    "Challenge Complete!": "도전 완료!",
    "Awesome!": "멋져요!",
    "First Steps": "첫걸음",
    "Write your first essay": "첫 번째 글을 쓰세요",
    "On a Roll": "잘하고 있어요",
    "Write for 3 days in a row": "3일 연속으로 글을 쓰세요",
    "Week Warrior": "주간 전사",
    "Write for 7 days in a row": "7일 연속으로 글을 쓰세요",
    "Month Master": "월간 마스터",
    "Write for 30 days in a row": "30일 연속으로 글을 쓰세요",
    "Word Builder": "단어 수집가",
    "Write 1,000 words total": "총 1,000단어를 쓰세요",
    "Word Smith": "단어 장인",
    "Write 10,000 words total": "총 10,000단어를 쓰세요",
    "Word Master": "단어 마스터",
    "Write 50,000 words total": "총 50,000단어를 쓰세요",
    "Prolific Writer": "다작가",
    "Write 10 essays": "10개의 글을 쓰세요",
    "Essay Machine": "글쓰기 기계",
    "Write 50 essays": "50개의 글을 쓰세요",
    "Going Public": "공개하기",
    "Publish your first public essay": "첫 번째 공개 글을 게시하세요",
    "Community Contributor": "커뮤니티 기여자",
    "Publish 10 public essays": "10개의 공개 글을 게시하세요",
    "Early Bird": "일찍 일어나는 새",
    "Write before 9 AM": "오전 9시 전에 글을 쓰세요",
    "Night Owl": "올빼미",
    "Write after 10 PM": "오후 10시 후에 글을 쓰세요",
    "Friends": "친구",
    "My Friends": "내 친구",
    "Friend Requests": "친구 요청",
    "Add Friend": "친구 추가",
    "Send Friend Request": "친구 요청 보내기",
    "Request Sent": "요청 보냄",
    "Already Friends": "이미 친구입니다",
    "Enter username": "사용자 이름 입력",
    "Search Result": "검색 결과",
    "Search": "검색",
    "wants to be friends": "님이 친구가 되고 싶어합니다",
    "No Friends Yet": "아직 친구가 없습니다",
    "Add friends to share your essays privately": "글을 비공개로 공유하려면 친구를 추가하세요",
    "Share Essay": "글 공유하기",
    "Select Friends": "친구 선택",
    "Shared!": "공유 완료!",
    "Successfully shared with %d friends!": "%d명의 친구와 성공적으로 공유했습니다!",
    "No keyword": "키워드 없음",
    "No friends yet. Add friends to share your writing!": "아직 친구가 없습니다. 글을 공유하려면 친구를 추가하세요!",
    "User not found": "사용자를 찾을 수 없습니다",
    "%d friends": "%d명의 친구",
    "Who can see this?": "누가 볼 수 있나요?",
    "Visibility": "공개범위",
    "Create Book": "책 만들기",
    "Edit Draft": "임시글 수정",
    "Edit Essay": "글 수정",
    "Your essay will be published as %@": "%@(으)로 게시됩니다",
    "Select Essays": "글 선택",
    "PDF": "PDF",
    "EPUB": "EPUB",
    "Book Title": "책 제목",
    "Author Name": "저자 이름",
    "Book Cover": "책 표지",
    "Include Table of Contents": "목차 포함",
    "Include Dates": "날짜 포함",
    "Export as": "내보내기 형식",
    "Generating...": "생성 중...",
    "Book Created!": "책이 생성되었습니다!",
    "Your book has been saved to Files": "책이 파일에 저장되었습니다",
    "Open in Files": "파일에서 열기",
    "Share Book": "책 공유하기",
    "%d essays selected": "%d개의 글 선택됨",
    "Select at least one essay": "최소 1개의 글을 선택하세요",
    "Table of Contents": "목차",
    "Essay %d": "글 %d"
]
